### ISSUE TITLE
Repo relationship to HHS or CDC

### ISSUE THREAD

**Issue by leebrian** [CareSet/COVID_Community_Profile_Report_FAQ#1]
Great project and I found your project through the link in the [healthdata.gov blog post](https://healthdata.gov/blog/covid-19-open-data-–-our-data-your-data). It's really helpful and answered many of my questions about data sources.

I think having a community driven FAQ is a great idea (especially since there isn't a non-community FAQ), is this FAQ solely community driven? Or does it have participation from HHS or CDC? If so, any chance the repo could be part of the [HHS](https://github.com/HHS) or [CDC](https://github.com/CDCgov) github organizations to help distinguish it from the large number of COVID-related projects.

**Comment by ftrotter** [comment]
Sorry for missing this...

This is definitely a community driven project. The only sense in which this is the "approved" resource (and I suspect the only sense it will be the approved resource in the future) is the fact that it was linked to by some tweets and press releases by HHS as a resource available from the community. 

While this project was born out of a collaboration between CDC, HHS and the whitehouse and the respective community participants, having this be unofficial was very much intentional. It allows us as people close to the project to provide commentary and context for the data that the agencies are not able to. It seems strange but the CDC is not really in a position to say "hey you should match this up with census data"... While the data is designed to correctly facilitate that kind of cross-pollination analysis (as the result of lots of work by all of those involved) the government must be extremely circumspect in what it says alongside public releases of data. 

hope this clarifies things..
-FT
